### ISSUE TITLE
Command missing in Mysql Tunneling article

### ISSUE THREAD

**Issue by oranges13** [emmercm/www#358]
Hello! First I wanted to thank you for your tunneling article because it was very helpful on a project that I'm working on. However, I wanted to highlight an error that had me stumped for a little bit and hopefully get it fixed so others won't end up in the same boat.

https://github.com/emmercm/www/blob/master/src/blog/tunneling-a-database-connection-with-docker-compose.md

The mysql command inside the `app` container is missing the `mysql` command.

```
app:
    image: alpine:latest
    command: sh -c "apk update && apk add mysql-client && MYSQL_PWD=poorpassword --host=mysql --port=3306 --user=dev --execute 'SELECT 1'"
    depends_on:
      - mysql
```

Should likely be:

```
app:
    image: alpine:latest
    command: sh -c "apk update && apk add mysql-client && MYSQL_PWD=poorpassword mysql --host=mysql --port=3306 --user=dev --execute 'SELECT 1'"
    depends_on:
      - mysql
```

Note the addition of the command `mysql` after MYSQL_PWD
